# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package -Dmaven.test.skip=true'
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'hb2.corele.top'
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjt6nzbFfEuDCU92Lk5cXKaeWvytZwQlLCd6w2lRBJ75BDIkNHHOcSS0xzerh9SDRwq8ugyN4pv2A6Y7xWjmO8491iZpR2gtIDGIHPQ6zGsgbsQdSyPio2uoKLxIj7zB2+0c+NdmDjGwmiAk06RRnMHjCx5NXF/uhPS2MwvCB6CynIMUgeS+V02igG3CKHGd3MIjhI0hhI4IVEnoosFkvoOonXK/YP32nen+fwGBKVa5LIYMhFzWltb5hMQaW0O002fzH1QD2DqvlafOB0xn37QWGagx4X6ZVZIMix6UC+Xt88sMauCUpnRMnTO/iusxNxAgLxsEealES0XuW73vI3 732007737@qq.com'
    sshKeySecureFile: '-----BEGIN OPENSSH PRIVATE KEY----- b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn NhAAAAAwEAAQAAAQEAo7ep82xXxLgwlPdi5OXFymnlr8rWcEJSwnesNpUQSe+QQyJDRxzn EktMc3q4fUg0cKvLoMjeKb9gOmO8Vo5jvOPdYmaUdoLSAxiBz0OsxrIG7EHUsj4qNrqCi8 SI+8wdvtHPjXZg4xsJogJNOkUZzB4wseTVxf7oT0tjMLwgegspyDFIHkvldNooBtwihxnd zCI4SNIYSOCFRJ6KLBZL6DqJ1yv2D99p3p/n8BgSlWuSyGDIRc1pbW+YTEGltDtNNn8x9U A9g6r5WnzgdMZ9+0FhmoMeF+mVWSDIselAvl7fPLDGrglKZ0TJ0zv4rrMTcQIC8bBHmpRE tF7lu97yNwAAA8iDQE9hg0BPYQAAAAdzc2gtcnNhAAABAQCjt6nzbFfEuDCU92Lk5cXKae WvytZwQlLCd6w2lRBJ75BDIkNHHOcSS0xzerh9SDRwq8ugyN4pv2A6Y7xWjmO8491iZpR2 gtIDGIHPQ6zGsgbsQdSyPio2uoKLxIj7zB2+0c+NdmDjGwmiAk06RRnMHjCx5NXF/uhPS2 MwvCB6CynIMUgeS+V02igG3CKHGd3MIjhI0hhI4IVEnoosFkvoOonXK/YP32nen+fwGBKV a5LIYMhFzWltb5hMQaW0O002fzH1QD2DqvlafOB0xn37QWGagx4X6ZVZIMix6UC+Xt88sM auCUpnRMnTO/iusxNxAgLxsEealES0XuW73vI3AAAAAwEAAQAAAQB8PC9XbWvc9/jF0kTV dhd11o5ZrA61+V5b+/xPHybRNF3A1AtBt4kRtNo693FwgI5qwbMwO7166KLZLD4LYNoGyN OCjF004WkEuGApLC28SfQ+7GW/LLVT+ox+C5H3oZkg6I4bxy0WqbnRmvWHtlAxOOey1vfx 29Hl+ks2/EuY0BDiEI8nx1QMTBszQ9qpRdXaBCjt32bUbVT3S29Ql1PkcvsnHDsilP3hOn FPpL3HSDAnLiZtZ4vj7/w6o1r3UElDXc1m1KXMl+MYpjq5v+KmsBgxhE2755RIEn/Vf6t0 7ztRl579YtUbH5jVAIsR+3Cl5QFoIs2r4RrUKPcre8VhAAAAgCl/5UsHJtoPwfs4XEHzJe Og9nrdGtKo/m6wXZzvoVuz3SLFCjqS0SuMxX7gK5Qw0SSyC7N6XTOdR2v3cgiG5A+hVzJU u5WxSSDrZUSy99SVKrlAwwRP8N3YkRVUjVE0Q/bfwAAkeLpKkvwNRGy1LBM5txqeiNYr9N W4QftkIv3EAAAAgQDUo5mHIaEdHWeNWwQmnujQeANBzQMkq/8XCXzhldOfX7sMfQpm0S76 mRije2ztmDWQR+CrH0cOBKHW3gfXL6seW4TnozFu0F5L7FWPo0yF28/smXKdBSb746NV3h 28fg44S3ayia6jUq0fKqn8BKSSmwzgyl0+cuyOkK1PwEUIUwAAAIEAxRo1M7w/Z5woLC/F YYkFOD1btbdqckkeP1KqCSKR9wfAk+3O8H/Q3LKtHrk0CuFiHgORHPzxVoL0Qjr6gPCv46 P8UyaKM8WoTmHlPpNHtMIs4FVb3miIaP2zmggJCSNptZPqsyf9Pe+byPGeJ88GJo+M8yPS qodDMitVcotjog0AAAAQNzMyMDA3NzM3QHFxLmNvbQECAw== -----END OPENSSH PRIVATE KEY-----'
